name: CI Build

# 触发条件：只要代码 push 到 main 分支就干活
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # GitHub 免费给你提供一台 Ubuntu 服务器

    steps:
      - name: 1. 拉取你的最新代码
        uses: actions/checkout@v4

      - name: 2. 安装 pnpm (关键步骤)
        uses: pnpm/action-setup@v4
        with:
          version: 9 # 使用最新的 pnpm 版本

      - name: 3. 安装 Node.js 20.15.0 环境
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.0"
          cache: "pnpm" # 架构师秘籍：开启 pnpm 缓存，下次构建秒级完成！

      - name: 4. 安装项目依赖
        run: pnpm install

      - name: 5. 执行自动构建打包
        run: pnpm run build
